"""AiOffice public Python API."""

from __future__ import annotations

from ._version import __version__
from .core import (
    AiOfficeError,
    Diagnostic,
    DiffEntry,
    DocumentDiff,
    ExportError,
    NativePackageError,
    RenderingError,
    SecurityError,
    Severity,
    SpecValidationError,
    UnsupportedFormatError,
    ValidationResult,
    WorkspaceError,
    new_id,
)
from .documents import (
    Document,
    DocumentBuilder,
    ImageAsset,
    PatchResult,
    open_artifact,
)
from .native import FidelityLevel, FidelityPolicy, FidelityReport
from .operations import TextMatch, TextRange
from .security import SecurityPolicy
from .spec import (
    AssetRef,
    BorderLine,
    ColumnLayout,
    DocumentDefaults,
    DocumentField,
    DocumentSection,
    DocumentSettings,
    HeaderFooterBindings,
    HeaderFooterPart,
    ImageBlock,
    ImageInsert,
    ImageUpdate,
    NamedStyle,
    PageSize,
    ParagraphBorders,
    ParagraphStyle,
    SectionColumn,
    SectionLayout,
    Table,
    TableBorders,
    TableCell,
    TableCellBorders,
    TableCellFormat,
    TableColumn,
    TableLayout,
    TableRow,
    TableWidth,
    TextStyle,
)
from .styles import ResolvedNamedStyle, resolve_named_style
from .rendering import (
    LIBREOFFICE_PROVIDER,
    PageVisualAnalysis,
    PaginatedRenderResult,
    RenderedPage,
    RenderOptions,
    RenderResult,
    VisualComparison,
    analyze_raster_page,
    compare_raster_images,
    libreoffice_render_capabilities,
)
from .workspace import Workspace

# The product specification intentionally exposes ``aioffice.open(...)``.
open = open_artifact

__all__ = [
    "AiOfficeError",
    "AssetRef",
    "BorderLine",
    "Diagnostic",
    "DiffEntry",
    "DocumentDiff",
    "Document",
    "DocumentBuilder",
    "DocumentField",
    "DocumentSection",
    "DocumentSettings",
    "DocumentDefaults",
    "ExportError",
    "FidelityLevel",
    "FidelityPolicy",
    "FidelityReport",
    "HeaderFooterBindings",
    "HeaderFooterPart",
    "ImageAsset",
    "ImageBlock",
    "ImageInsert",
    "ImageUpdate",
    "LIBREOFFICE_PROVIDER",
    "NativePackageError",
    "NamedStyle",
    "PageSize",
    "PageVisualAnalysis",
    "PaginatedRenderResult",
    "PatchResult",
    "ParagraphBorders",
    "ParagraphStyle",
    "ColumnLayout",
    "RenderOptions",
    "RenderResult",
    "RenderingError",
    "RenderedPage",
    "Severity",
    "SecurityError",
    "SecurityPolicy",
    "SpecValidationError",
    "Table",
    "TableBorders",
    "TableCell",
    "TableCellBorders",
    "TableCellFormat",
    "TableColumn",
    "TableLayout",
    "TableRow",
    "TableWidth",
    "TextMatch",
    "TextRange",
    "TextStyle",
    "SectionColumn",
    "SectionLayout",
    "UnsupportedFormatError",
    "ValidationResult",
    "VisualComparison",
    "Workspace",
    "WorkspaceError",
    "__version__",
    "analyze_raster_page",
    "compare_raster_images",
    "libreoffice_render_capabilities",
    "new_id",
    "open",
    "open_artifact",
    "resolve_named_style",
    "ResolvedNamedStyle",
]
