"""AiOffice Spec 0.2 draft models and serialization helpers."""

from .models import (
    AiOfficeDocumentSpec,
    ArtifactDescriptor,
    Block,
    BulletList,
    DocumentMetadata,
    Heading,
    Length,
    LineSpacing,
    NativeRef,
    OpaqueBlock,
    OrderedList,
    PageBreak,
    Paragraph,
    ParagraphStyle,
    Table,
    TableColumn,
    TableRow,
    TextSpan,
    TextStyle,
    ThemeRef,
)

__all__ = [
    "AiOfficeDocumentSpec",
    "ArtifactDescriptor",
    "Block",
    "BulletList",
    "DocumentMetadata",
    "Heading",
    "Length",
    "LineSpacing",
    "NativeRef",
    "OpaqueBlock",
    "OrderedList",
    "PageBreak",
    "Paragraph",
    "ParagraphStyle",
    "Table",
    "TableColumn",
    "TableRow",
    "TextSpan",
    "TextStyle",
    "ThemeRef",
]
